### ISSUE TITLE
Document the Ops + QA pipeline process

### ISSUE THREAD

**Issue by stephendonner** [mozilla/firefox-test-engineering#9]
Document the Ops + QA pipeline process

**Comment by stephendonner** [comment]
Made good headway in https://github.com/mozilla/firefox-test-engineering/commit/6059d68c25500644f6f2f6e3480ecd6e319cf87e

**Comment by rpappalax** [comment]
Per our 9/27 mtg (@stephendonner & @rpappalax):
we'll need to run the QAJenkinsProd tests on QAJenkinsDev to properly vet the plugins (those tests should by definition be stable).  If we run the QAJenkinsPrePred tests on QAJenkinsDev, those tests are under heavy development and will not be reliable for plugin vetting.
